### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by peggyl** [aheckmann/node-email#25]
I want to use [Sourcegraph](https://sourcegraph.com) for node-email code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/aheckmann/node-email. (It should only take 30 seconds.)

Inspired by: [What is Code?](http://www.bloomberg.com/graphics/2015-paul-ford-what-is-code/) "Sending an email" steps 1-4. :)

Thanks!

**Comment by aheckmann** [comment]
Closing. This project is no longer maintained.
