### ISSUE TITLE
How can I prevent double quotes from being quoted?

### ISSUE THREAD

**Issue by soichih** [aheckmann/node-email#27]
I've noticed that the content of body is automatically quote-escaped.

Like.. If I send following email

```
var Email = require('email').Email
var myMsg = new Email(
{ from: "hayashis@iu.edu",
to:   "hayashis@iu.edu"
, subject: "Knock knock..."
, body: "Who's there? \"quote test\""
})
```

I will receive an email like

```
Who's there? \"quote test\"
```

So it looks like node-email is doing unnecessary(?) escaping of the double quotes. How can I prevent this?

**Comment by aheckmann** [comment]
Closing. This project is no longer maintained.
